# Generated by Django 4.1.3 on 2022-11-11 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import musics.constants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('track_id', models.CharField(default='None', max_length=255)),
                ('genre', models.CharField(choices=[('me', 'movie'), ('rb', 'r&b'), ('aa', 'a capella'), ('ae', 'alternative'), ('cy', 'country'), ('de', 'dance'), ('ec', 'electronic'), ('am', 'anime'), ('fk', 'folk'), ('bs', 'blues'), ('oa', 'opera'), ('hp', 'hip-hop'), ('cc', 'children’s music'), ('rp', 'rap'), ('ie', 'indie'), ('cl', 'classical'), ('pp', 'pop'), ('re', 'reggae'), ('rn', 'reggaeton'), ('jz', 'jazz'), ('rk', 'rock'), ('sa', 'ska'), ('cd', 'comedy'), ('sl', 'soul'), ('sk', 'soundtrack'), ('wd', 'world')], default=('me', 'movie'), max_length=2)),
                ('cluster_class', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Musics',
                'ordering': ['genre'],
            },
        ),
        migrations.CreateModel(
            name='LibraryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('play_random', models.BooleanField(default=False)),
                ('use_ai', models.BooleanField(default=True)),
                ('musics', models.JSONField(default=musics.constants.models.MUSICS_DEFAULT)),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Library',
                'verbose_name_plural': 'Librarys',
                'ordering': ['user_owner'],
            },
        ),
    ]
