# Generated by Django 4.1.3 on 2022-11-08 19:46

from django.db import migrations, models
import django.db.models.deletion
import photographer_assistent.constants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('track_id', models.CharField(default='None', max_length=255)),
                ('genre', models.CharField(choices=[('RK', 'Rock')], default=('RK', 'Rock'), max_length=2)),
                ('cluster_class', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('play_random', models.BooleanField(default=False)),
                ('use_ai', models.BooleanField(default=True)),
                ('musics', models.JSONField(default=photographer_assistent.constants.models.MUSICS_DEFAULT)),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.usermodel')),
            ],
        ),
    ]
