# Generated by Django 4.1.3 on 2022-11-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer_assistent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarymodel',
            options={'ordering': ['user_owner'], 'verbose_name': 'Library', 'verbose_name_plural': 'Librarys'},
        ),
        migrations.AlterModelOptions(
            name='musicmodel',
            options={'ordering': ['genre'], 'verbose_name': 'Music', 'verbose_name_plural': 'Musics'},
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='genre',
            field=models.CharField(choices=[('me', 'movie'), ('rb', 'r&b'), ('aa', 'a capella'), ('ae', 'alternative'), ('cy', 'country'), ('de', 'dance'), ('ec', 'electronic'), ('am', 'anime'), ('fk', 'folk'), ('bs', 'blues'), ('oa', 'opera'), ('hp', 'hip-hop'), ('cc', 'children’s music'), ('rp', 'rap'), ('ie', 'indie'), ('cl', 'classical'), ('pp', 'pop'), ('re', 'reggae'), ('rn', 'reggaeton'), ('jz', 'jazz'), ('rk', 'rock'), ('sa', 'ska'), ('cd', 'comedy'), ('sl', 'soul'), ('sk', 'soundtrack'), ('wd', 'world')], default=('me', 'movie'), max_length=2),
        ),
    ]
