# Generated by Django 4.1.3 on 2022-11-30 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtokens',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tokensblacklist',
            name='key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jwt_auth.refreshtokens'),
        ),
    ]
