# Generated by Django 4.1.3 on 2022-12-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_alter_refreshtokens_user_alter_tokensblacklist_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refreshtokens',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tokensblacklist',
            name='id',
        ),
        migrations.AddField(
            model_name='refreshtokens',
            name='user_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='refreshtokens',
            name='key',
            field=models.CharField(max_length=1200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tokensblacklist',
            name='key',
            field=models.CharField(max_length=1200, primary_key=True, serialize=False, unique=True),
        ),
    ]
