# Generated by Django 4.1.3 on 2022-12-02 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_remove_refreshtokens_user_remove_tokensblacklist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokensblacklist',
            name='exp',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 2, 3, 7, 545436, tzinfo=datetime.timezone.utc)),
        ),
    ]
