# Generated by Django 4.1.3 on 2022-12-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0007_alter_tokensblacklist_exp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokensBlackList',
        ),
        migrations.AddField(
            model_name='refreshtokens',
            name='ass',
            field=models.IntegerField(default=1),
        ),
    ]
