# Generated by Django 4.1.3 on 2022-11-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarymodel',
            name='play_random',
        ),
        migrations.RemoveField(
            model_name='librarymodel',
            name='use_ai',
        ),
    ]
