# Generated by Django 4.1.3 on 2022-11-17 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStaticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_using', models.TimeField(blank=True, null=True)),
                ('clustering_stats', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user_static',
                'verbose_name_plural': 'user_statics',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(default='U', max_length=1)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='ColorConfigsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('menu_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('button_color', models.CharField(default='#000000', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('music_background_color', models.CharField(default='#A6A6A6', max_length=7)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'color_config',
                'verbose_name_plural': 'color_configs',
                'ordering': ['user'],
            },
        ),
    ]
