# Generated by Django 4.1.3 on 2022-11-08 19:46

import account.constants.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login_date', models.DateField(default=django.utils.timezone.now)),
                ('time_using', models.TimeField()),
                ('clustering_stats', models.JSONField()),
                ('last_songs', models.JSONField(default=account.constants.models.LAST_SONGS_DEFAULT)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.IntegerField()),
                ('genre', models.CharField(default=('U', 'Undefined'), max_length=1)),
                ('created_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColorConfigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('menu_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('button_color', models.CharField(default='#000000', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('music_background_color', models.CharField(default='#A6A6A6', max_length=7)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
