# Generated by Django 4.1.3 on 2022-11-08 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorconfigs',
            options={'ordering': ['user'], 'verbose_name': 'color_config', 'verbose_name_plural': 'color_configs'},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['user'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userstatics',
            options={'ordering': ['user'], 'verbose_name': 'user_static', 'verbose_name_plural': 'user_statics'},
        ),
    ]
