# Generated by Django 4.1.3 on 2022-11-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='country_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
