# Generated by Django 4.1.3 on 2022-11-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_usermodel_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstaticsmodel',
            name='clustering_stats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstaticsmodel',
            name='time_using',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
