# Generated by Django 4.1.3 on 2022-11-08 20:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_alter_colorconfigs_options_alter_usermodel_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColorConfigs',
            new_name='ColorConfigsModel',
        ),
        migrations.RenameModel(
            old_name='UserStatics',
            new_name='UserStaticsModel',
        ),
    ]
