# Generated by Django 4.1.3 on 2022-12-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_usermodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='photo',
            field=models.ImageField(default='default_user.webp', upload_to='profile_pic'),
        ),
    ]
